### ISSUE TITLE
tool load error

### ISSUE THREAD

**Issue by jiangfw** [misakuo/JsonModelGenerator#1]
EmptyThrowable: Null child action in group Main Toolbar () of class class com.intellij.openapi.actionSystem.DefaultActionGroup, id=Moxun.generator

**Comment by misakuo** [comment]
I think the problem is caused by JRE or JDK version, the plugin is compiled by JDK1.7, I've complied  [this zip file](http://pan.baidu.com/s/1pKt2YN5) with JDK1.6, can you help me test it please?

**Comment by jiangfw** [comment]
I'm sorry, but I still failed.I used the android studio version 1.5.1.I think it is related to the android studio version.thanks.

**Comment by misakuo** [comment]
Hi, I just updated a new version [here](https://github.com/misakuo/JsonModelGenerator/blob/master/ModelGenerator.zip) and already upload to [repo](https://plugins.jetbrains.com/plugin/8062?pr=), I think the crash is resolved. could you try it again?
